# Generated by Django 4.2 on 2024-12-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshelfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('weight', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
