# Generated by Django 4.2 on 2024-12-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshelfapp', '0003_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='code',
            new_name='number',
        ),
    ]
