# Generated by Django 4.2 on 2024-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshelfapp', '0004_rename_code_shelf_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='number',
            field=models.IntegerField(),
        ),
    ]
